# Generated by Django 6.0.3 on 2026-06-12 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='案件名')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('deadline', models.DateTimeField(verbose_name='提出期限')),
                ('info_message', models.TextField(blank=True, verbose_name='お知らせ')),
                ('copy_guide_message', models.TextField(blank=True, verbose_name='コピー案内メッセージ')),
                ('confirm_message', models.TextField(blank=True, verbose_name='確認画面メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, verbose_name='役割')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='shift.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '担当者',
                'verbose_name_plural': '担当者',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='シフト名')),
                ('short_name', models.CharField(blank=True, max_length=3, verbose_name='略称')),
                ('time_range', models.CharField(blank=True, max_length=30, verbose_name='時間帯')),
                ('color', models.CharField(default='#2563eb', max_length=7, verbose_name='カラー')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='shift.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'シフト枠',
                'verbose_name_plural': 'シフト枠',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='コード')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='shift.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted', models.BooleanField(default=False, verbose_name='提出済み')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('notes', models.TextField(blank=True, verbose_name='特記事項')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='shift.project', verbose_name='案件')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='shift.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '提出',
                'verbose_name_plural': '提出',
                'unique_together': {('project', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('shift_types', models.ManyToManyField(blank=True, to='shift.shifttype', verbose_name='シフト')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='shift.submission', verbose_name='提出')),
            ],
            options={
                'verbose_name': 'シフト選択',
                'verbose_name_plural': 'シフト選択',
                'ordering': ['date'],
                'unique_together': {('submission', 'date')},
            },
        ),
    ]
