# Generated by Django 6.0.3 on 2026-06-12 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='token',
        ),
        migrations.AddField(
            model_name='project',
            name='auth_mode',
            field=models.CharField(choices=[('name', '名前入力モード'), ('code', 'コード＋パスワードモード')], default='name', max_length=10, verbose_name='認証モード'),
        ),
        migrations.AddField(
            model_name='project',
            name='submit_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='パスワード'),
        ),
    ]
